# Note:
# Make sure that the github pages is already set to Github Actions, otherwise the workflow will fail.
#
# Author: Shubham Gupta
# GitHub: https://github.com/shubham16g/
# Created On: 5 Aug, 2022
# Updated On: 18 May, 2024

name: CI
on:
  push:
    branches:
      - master
#  pull_request:
#    branches:
#      - master

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  flutter_web_deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    # If you want to change the directory to run commands
    #    defaults:
    #      run:
    #        working-directory: ./sub-folder
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.1'
      - run: flutter pub get
      - run: flutter build web --base-href /${{ github.event.repository.name }}/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: web-build
          #          path: sub-folder/build/web // if working-directory is changed
          path: build/web
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2